### ISSUE TITLE
Event link in Events page should link through to day page 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#987]
Right now, calendar date links through to http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/2015-11-19

On News & Events, page, user can click through to date (e.g. Nov 19) - but instead is shows the full months

**Comment by limage** [comment]
@MagdiRizkallah Please assign to back end for changing of "Event link in Events page should link through to day page", thanks!

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Please help!

**Comment by erica-scott** [comment]
Completed by making slight changes to the view. The links now link to the day calendar instead of the month one.

**Comment by MagdiRizkallah** [comment]
@erica-scott It links to the week calendar for me. e.g. when you click on the 7 Feb, you get to: http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/2016-02-07

**Comment by erica-scott** [comment]
The code has been double checked and it is correct. The code needs to be pulled to the dev site and 'drush fra' needs to be run.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Please note the above comment from Erica!

**Comment by bensinjin** [comment]
done.

**Comment by PeaceGeeksProjects** [comment]
Thanks @bensinjin & @erica-scott .  HOWEVER, it is still not working smoothly.

clicking on the 7 Feb on the calendar sends you to http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/2016-02-07 which is a 'week' view with the day highlighted.  But the Prev and Next buttons move by a month at a time (should probably be either a week at a time or a day at a time - I would prefer prev event or next event)

Moving back to in progress.

**Comment by erica-scott** [comment]
I also noticed that it's still not working. Sorry about that, I'm going to take this back and do some serious digging because I'm having trouble figuring out why that is?

**Comment by erica-scott** [comment]
I'm wondering if there was a delay in code being pushed/reacting to the push/etc. because while searching for this issue, at one point clicking on the link on the dev site took me to the proper place. Based on my testing, this is now definitely working on the dev site.

What it will do now, is instead of redirecting to http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/2016-02-07 (which takes it to the 'month' view but giving it a full date makes it appear differently) it will now redirect to http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-02-07 which shows the event on that day, and the Prev/Next buttons move by a day at a time.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
